# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-19 17:41
from __future__ import unicode_literals

import cloud.utils.model_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=cloud.utils.model_utils.generate_uuid)),
                ('store_id', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
    ]
